[project]
name = "pytorch-course"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10,<3.13"
dependencies = [
    "ipykernel>=6.25.0",
    "jupyter>=1.0.0",
    "matplotlib>=3.10.7",
    "notebook>=7.0.0",
    "numpy>=1.24.0,<2.0.0",
    "torch>=2.0.0",
]
